[base]
debug_mode = "debug"
time_location = "Asia/Beijing"
[http]
addr = ":8880"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20
allow_ip = [
    "127.0.0.1"
]
[session]
redis_server = "127.0.0.1:3600"
redis_password = ""
[log]
log_level = "trace"
[log.file_write]
on = true
log_path = "./logs/gateway.log"
rotate_log_path = "./logs/gateway.log.%Y%M%D%H"
wf_log_path = "./logs/gateway.wf.log"
rotate_wf_log_path = "./logs/gateway.wf.log.%Y%M%D%H"
[log.console_write]
on = true
color = true
[cluster]
cluster_ip = "127.0.0.1"
cluster_port = "8080"
cluster_ssl_port = "4433"
[swagger]
title = "gateway swagger API"
desc = ""
host = "127.0.0.1:8880"
base_path = ""
version = "1.0"
schemes = ["http", "https"]